[workspace]
pr_name = "repo: release"
pr_branch_prefix = "release-plz/"
pr_labels = ["autorelease"]
changelog_update = false
git_tag_name = "{{ package }}-v{{ version }}"

[[package]]
name = "bestool"
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
semver_check = false
