#!/usr/bin/bash

date_store=""
time_store=""
while true; do
	date_current="$(date +%Y-%m-%d)"
	if [[ "$date_store" != "$date_current" ]]; then
		date_store="$date_current"
		bestool iti lcd send '{"layout":[
			{"x":100,"y":14,"fill":[0,0,0],"width":100,"height":20},
			{"x":100,"y":30,"stroke":[235,225,205],"text":"'"$date_store"'"}
		]}'
	fi

	time_current="$(date +%H:%M)"
	if [[ "$time_store" != "$time_current" ]]; then
		time_store="$time_current"
		bestool iti lcd send '{"layout":[
			{"x":220,"y":14,"fill":[0,0,0],"width":50,"height":20},
			{"x":220,"y":30,"stroke":[235,225,205],"text":"'"$time_store"'"}
		]}'
	fi

	sleep 10
done
