#!/usr/bin/bash

update() {
	jq -n \
		--argjson y 80 \
		--arg hostname "$(hostname)" \
		--argjson ips "$(ip -4 -j a show up scope global)" \
	'
		["\($hostname).local", [$ips[].addr_info[].local | select(. != null)][:2][]]
		| [.[] | if (.|length <= 26) then . else "\(.[:20])\n  \(.[20:])" end]
		| join("\n\n")
		| {layout:[
			{x:10,y:($y-15),fill:[0,0,0],width:260,height:((. | split("\n") | length)*20)},
			{x:10,y:$y,stroke:[220,0,220],text:.}
		]}
	' | tee /dev/stderr | bestool iti lcd send
}

while true; do
	update
	sleep 60
done
