publish = true
tag-message = "release: rpi-st7789v2-driver {{version}}"
pre-release-commit-message = "release: rpi-st7789v2-driver {{version}}"
pre-release-hook = ["git", "cliff", "-r", "../..", "-c", "../../cliff.toml", "-o", "../../CHANGELOG.md", "--tag", "{{version}}"]
