publish = true
tag-message = "release: improv-wifi {{version}}"
pre-release-commit-message = "release: improv-wifi {{version}}"
pre-release-hook = ["git", "cliff", "-r", "../..", "-c", "../../cliff.toml", "-o", "../../CHANGELOG.md", "--tag", "{{version}}"]
