name: Typos Check
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          config: .typos.toml
